name: CI/CD configurtion workflows

on:
  push:
    branches: [ main ]

## setting the environment
env:
  GLOBAL_VARIABLE: global_value

## setting up jobs 
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      JOB_VARIABLE: job_value

    steps:
      
      - name: checking out code
        uses: actions/checkout@v4

      - name: setting up python version
        uses: actions/setup-python@v4
        with:
            python-version: "3.10.13"

      - name: installing dependecies 
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest

      - name: checking the running
        run: |
          echo "global_variable: ${{env.GLOBAL_VARIABLE}}"
          echo "local_variable: ${{env.JOB_VARIABLE}}"
          
      - name: running pytests
        run: |
          pytest

## setting up autonomous building environment
  build-and-deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: creating docker images 
        uses: docker/setup-buildx-action@v2

      - name: login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Building and pushing Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/docker-cicd-app:latest

      - name: image digest 
        run: |
          echo ${{steps.build-and-deploy.digest}}


          
