name : CI/CD workflows for Dockerized Flask App

on:
  ## triggering a workflows with push event on branch main 
  push : 
    branches: [ main ]

jobs:
  build-and-test:
    # running on the ubuntu latest runner virtual machine 
    runs-on: ubuntu-latest

    steps:
      ## checking out the code 
      - name: checking out the code
        uses: actions/checkout@v4
      
      ## setting up the python versions 
      - name: setting up python 
        uses: actions/setup-python@v4
        with: 
          python-version : '3.9'

      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install flask
          pip install pytest 

