name: CI/CD configurtion workflows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v4

      - name: setting up python version
        uses: actions/setup-python@v4

      - name: installing dependecies 
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest

      - name: checking the running
        run: |
          echo "Hello world! $(naomi)"

