name: CI/CD configurtion workflows

on:
  push:
    branches: [ main ]

## setting the environment
env:
  GLOBAL_VARIABLE: global_value

## setting up jobs 
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JOB_VARIABLE: job_value

    steps:
      
      - name: checking out code
        uses: actions/checkout@v4

      - name: setting up python version
        uses: actions/setup-python@v4

      - name: installing dependecies 
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest

      - name: checking the running
        run: |
          echo "global_variable: ${{env.GLOBAL_VARIABLE}}"
          echo "local_variable: ${{env.JOB_VARIABLE}}"
          

